version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - .env

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --workers=4 config.wsgi:application --bind 0.0.0.0:8000 && python3 manage.py migrate
    restart: always
    volumes:
      - ./static:/var/www/static
      - ./media:/var/www/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my-network: